server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teleMedicine?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaforfun127@gmail.com
    password: wsva xyvh wrlf ihcg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

mailServer:
  host: smtp.gmail.com
  port: 587
  email: javaforfun127@gmail.com
  password: r j m t z o k f h o v x s h y d
  protocol: smtp
  isSSL: false



jwt:
  accessToken: "oGuan+rlGCKCbL7pNKWTXd105C0QN0EOxs4zntzEPtCg3ZQPq9ivt1dm9COrDXPY"
#  thời gian hết hạn token theo đơn vị giây
  valid-duration: 3600
#  thời gian có thể refresh token
  refreshable-duration: 36000