server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teleMedicine?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #    open-in-view: false  # Hạn chế vấn đề với session Hibernate ngoài phạm vi giao dịch
  mvc:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: javaforfun127@gmail.com
    password: wsva xyvh wrlf ihcg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

mailServer:
  host: smtp.gmail.com
  port: 587
  email: javaforfun127@gmail.com
  password: r j m t z o k f h o v x s h y d
  protocol: smtp
  isSSL: false
cloudinary:
  cloud-name: dkcn9vpuy
  api-key: 136272232281289
  secret-key: OB7tNZdLb222OCnGCbcz2-nkess





jwt:
  accessToken: "oGuan+rlGCKCbL7pNKWTXd105C0QN0EOxs4zntzEPtCg3ZQPq9ivt1dm9COrDXPY"
  expiryTime: 3600 #Thời gian hết hạn của token theo giây
  refreshToken: "TmaYX9O/HJjGlI7CKMLGnYv8lFfAkaaRW6mb90AWRNYAUyz4sEI0cUSfVTLrromU"
  expiryTimeRefreshToken: 36000 #Thời gian hết hạn refresh