server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teleMedicine
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  accessToken: "oGuan+rlGCKCbL7pNKWTXd105C0QN0EOxs4zntzEPtCg3ZQPq9ivt1dm9COrDXPY"
#  thời gian hết hạn token theo đơn vị giây
  valid-duration: 3600
#  thời gian có thể refresh token
  refreshable-duration: 36000